{
	"results":[
		{
			"platform_user_id":"3",
			"role":"User",
			"username":"test",
			"firstName":"Testing",
			"lastName":"Test",
			"email":"test@test.com"
		},
		{
			"platform_user_id":"2",
			"role":"User",
			"username":"miki",
			"firstName":"Miki",
			"lastName":"Miška",
			"email":"miki.miska@disney.com"
		},
		{
			"platform_user_id":"1",
			"role":"Administrator",
			"username":"alesl",
			"firstName":"Aleš",
			"lastName":"Lončar",
			"email":"ales@creatoor.com"
		}
	],
	"totalcount":3,
	"status":"success"
}
